// Generated by Selenium IDE
package org.ual.hmis.equipo20;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
import org.openqa.selenium.firefox.FirefoxOptions;
import org.openqa.selenium.chrome.ChromeOptions;
public class BotonesinferioresprincipalTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
	    // Browser selector
	    int browser= 0; // 0: firefox, 1: chrome,...
	    Boolean headless = false;

	    switch (browser) {
	    case 0:  // firefox
	    	// Firefox
	    	// Descargar geckodriver de https://github.com/mozilla/geckodriver/releases
	    	// Descomprimir el archivo geckodriver.exe en la carpeta drivers

	    	System.setProperty("webdriver.gecko.driver",  "drivers/geckodriver.exe");
	    	FirefoxOptions firefoxOptions = new FirefoxOptions();
	    	firefoxOptions.setHeadless(true);
	    	driver = new FirefoxDriver(firefoxOptions);

	    	break;
	    case 1: // chrome
	    	// Chrome
	    	// Descargar Chromedriver de https://chromedriver.chromium.org/downloads
	    	// Descomprimir el archivo chromedriver.exe en la carpeta drivers

	    	System.setProperty("webdriver.chrome.driver", "drivers/chromedriver.exe");
	    	ChromeOptions chromeOptions = new ChromeOptions();
	    	chromeOptions.setHeadless(true);
	    	chromeOptions.addArguments("window-size=1920,1080");
	    	driver = new ChromeDriver(chromeOptions);

	    	break;

	    default:
	    	fail("Please select a browser");
	    	break;
	    }
	    js = (JavascriptExecutor) driver;
	    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void botongithubrepo() {
    // Test name: boton-github-repo
    // Step # | name | target | value
    // 1 | open | https://hmis2023-sesion04-freeweb.azurewebsites.net/index.html | 
    driver.get("https://hmis2023-sesion04-freeweb.azurewebsites.net/index.html");
    // 2 | setWindowSize | 1021x727 | 
    driver.manage().window().setSize(new Dimension(1021, 727));
    // 3 | click | css=li:nth-child(1) > .icon | 
    driver.findElement(By.cssSelector("li:nth-child(1) > .icon")).click();
    // 4 | assertText | id=repository-container-header | AlejandroTSoto\n/\nSesion04-2023\nPublic\nPin\nUnwatch 1\nFork 1\nFork your own copy of AlejandroTSoto/Sesion04-2023\nStar 0\nCode\nIssues\nPull requests\nActions\nProjects\nWiki\nSecurity\nInsights\nSettings
    assertThat(driver.findElement(By.id("repository-container-header")).getText(), is("AlejandroTSoto\\\\n/\\\\nSesion04-2023\\\\nPublic\\\\nPin\\\\nUnwatch 1\\\\nFork 1\\\\nFork your own copy of AlejandroTSoto/Sesion04-2023\\\\nStar 0\\\\nCode\\\\nIssues\\\\nPull requests\\\\nActions\\\\nProjects\\\\nWiki\\\\nSecurity\\\\nInsights\\\\nSettings"));
  }
  @Test
  public void nobotongithubrepo() {
    // Test name: no-boton-github-repo
    // Step # | name | target | value
    // 1 | open | https://hmis2023-sesion04-freeweb.azurewebsites.net/index.html | 
    driver.get("https://hmis2023-sesion04-freeweb.azurewebsites.net/index.html");
    // 2 | setWindowSize | 1021x727 | 
    driver.manage().window().setSize(new Dimension(1021, 727));
    // 3 | click | css=li:nth-child(1) > .icon | 
    driver.findElement(By.cssSelector("li:nth-child(1) > .icon")).click();
    // 4 | assertNotText | id=repository-container-header | AlejandroTSoto\n/\nSesion04-2023\nPublic\nPin\nUnwatch 1\nFork 1\nFork your own copy of AlejandroTSoto/Sesion04-2023\nStar 0\nCode\nIssues\nPull requests\nActions\nProjects\nWiki\nSecurity\nInsights\nSettings
    assertThat(driver.findElement(By.id("repository-container-header")).getText(), is(not("AlejandroTSoto\\\\n/\\\\nSesion04-2023\\\\nPublic\\\\nPin\\\\nUnwatch 1\\\\nFork 1\\\\nFork your own copy of AlejandroTSoto/Sesion04-2023\\\\nStar 0\\\\nCode\\\\nIssues\\\\nPull requests\\\\nActions\\\\nProjects\\\\nWiki\\\\nSecurity\\\\nInsights\\\\nSettings")));
  }
  @Test
  public void botondocumentaciongithub() {
    // Test name: boton-documentacion-github
    // Step # | name | target | value
    // 1 | open | https://hmis2023-sesion04-freeweb.azurewebsites.net/index.html | 
    driver.get("https://hmis2023-sesion04-freeweb.azurewebsites.net/index.html");
    // 2 | setWindowSize | 1021x727 | 
    driver.manage().window().setSize(new Dimension(1021, 727));
    // 3 | click | css=li:nth-child(2) > .icon | 
    driver.findElement(By.cssSelector("li:nth-child(2) > .icon")).click();
    // 4 | assertText | css=.flex-justify-between | Documentación de GitHub\nVersion: Free, Pro, & Team\nDocumentación de Github de búsqueda
    assertThat(driver.findElement(By.cssSelector(".flex-justify-between")).getText(), is("Documentación de GitHub\\\\nVersion: Free, Pro, & Team\\\\nDocumentación de Github de búsqueda"));
  }
  @Test
  public void nobotondocumentaciongithub() {
    // Test name: no-boton-documentacion-github
    // Step # | name | target | value
    // 1 | open | https://hmis2023-sesion04-freeweb.azurewebsites.net/index.html | 
    driver.get("https://hmis2023-sesion04-freeweb.azurewebsites.net/index.html");
    // 2 | setWindowSize | 1021x727 | 
    driver.manage().window().setSize(new Dimension(1021, 727));
    // 3 | click | css=li:nth-child(2) > .icon | 
    driver.findElement(By.cssSelector("li:nth-child(2) > .icon")).click();
    // 4 | assertNotText | css=.flex-justify-between | Documentación de GitHub\nVersion: Free, Pro, & Team\nDocumentación de Github de búsqueda
    assertThat(driver.findElement(By.cssSelector(".flex-justify-between")).getText(), is(not("Documentación de GitHub\\\\nVersion: Free, Pro, & Team\\\\nDocumentación de Github de búsqueda")));
  }
  @Test
  public void botonazure() {
    // Test name: boton-azure
    // Step # | name | target | value
    // 1 | open | https://hmis2023-sesion04-freeweb.azurewebsites.net/index.html | 
    driver.get("https://hmis2023-sesion04-freeweb.azurewebsites.net/index.html");
    // 2 | setWindowSize | 1021x727 | 
    driver.manage().window().setSize(new Dimension(1021, 727));
    // 3 | click | css=li:nth-child(5) > .icon | 
    driver.findElement(By.cssSelector("li:nth-child(5) > .icon")).click();
    // 4 | assertText | id=_weave_e_56 | Todo
    assertThat(driver.findElement(By.id("_weave_e_56")).getText(), is("Todo"));
  }
  @Test
  public void botondocumentacionazure() {
    // Test name: boton-documentacion-azure
    // Step # | name | target | value
    // 1 | open | https://hmis2023-sesion04-freeweb.azurewebsites.net/index.html | 
    driver.get("https://hmis2023-sesion04-freeweb.azurewebsites.net/index.html");
    // 2 | setWindowSize | 1021x727 | 
    driver.manage().window().setSize(new Dimension(1021, 727));
    // 3 | click | css=li:nth-child(6) > .icon | 
    driver.findElement(By.cssSelector("li:nth-child(6) > .icon")).click();
    // 4 | assertText | id=hero-title | Documentación de Azure
    assertThat(driver.findElement(By.id("hero-title")).getText(), is("Documentación de Azure"));
  }
  @Test
  public void botongit() {
    // Test name: boton-git
    // Step # | name | target | value
    // 1 | open | https://hmis2023-sesion04-freeweb.azurewebsites.net/index.html | 
    driver.get("https://hmis2023-sesion04-freeweb.azurewebsites.net/index.html");
    // 2 | setWindowSize | 1021x727 | 
    driver.manage().window().setSize(new Dimension(1021, 727));
    // 3 | click | css=.fa-git-alt | 
    driver.findElement(By.cssSelector(".fa-git-alt")).click();
    // 4 | assertText | css=h1 | Book
    assertThat(driver.findElement(By.cssSelector("h1")).getText(), is("Book"));
  }
  @Test
  public void botonhtml5() {
    // Test name: boton-html5
    // Step # | name | target | value
    // 1 | open | https://hmis2023-sesion04-freeweb.azurewebsites.net/index.html | 
    driver.get("https://hmis2023-sesion04-freeweb.azurewebsites.net/index.html");
    // 2 | setWindowSize | 1021x727 | 
    driver.manage().window().setSize(new Dimension(1021, 727));
    // 3 | click | linkText=HTML5 UP | 
    driver.findElement(By.linkText("HTML5 UP")).click();
    // 4 | assertText | css=.about | ... makes spiffy HTML5\nsite templates that are:
    assertThat(driver.findElement(By.cssSelector(".about")).getText(), is("... makes spiffy HTML5\\\\nsite templates that are:"));
  }
  @Test
  public void botonrepohmis() {
    // Test name: boton-repo-hmis
    // Step # | name | target | value
    // 1 | open | https://hmis2023-sesion04-freeweb.azurewebsites.net/index.html | 
    driver.get("https://hmis2023-sesion04-freeweb.azurewebsites.net/index.html");
    // 2 | setWindowSize | 1021x727 | 
    driver.manage().window().setSize(new Dimension(1021, 727));
    // 3 | click | css=li:nth-child(3) > .icon | 
    driver.findElement(By.cssSelector("li:nth-child(3) > .icon")).click();
    // 4 | assertText | css=.flex-1 > .color-fg-muted > div | Grado en Ingeniería Informática -Universidad de Almería
    assertThat(driver.findElement(By.cssSelector(".flex-1 > .color-fg-muted > div")).getText(), is("Grado en Ingeniería Informática -Universidad de Almería"));
  }
  @Test
  public void nobotonazure() {
    // Test name: no-boton-azure
    // Step # | name | target | value
    // 1 | open | https://hmis2023-sesion04-freeweb.azurewebsites.net/index.html | 
    driver.get("https://hmis2023-sesion04-freeweb.azurewebsites.net/index.html");
    // 2 | setWindowSize | 1021x727 | 
    driver.manage().window().setSize(new Dimension(1021, 727));
    // 3 | click | css=li:nth-child(5) > .icon | 
    driver.findElement(By.cssSelector("li:nth-child(5) > .icon")).click();
    // 4 | assertNotText | id=_weave_e_56 | Todo
    assertThat(driver.findElement(By.id("_weave_e_56")).getText(), is(not("Todo")));
  }
  @Test
  public void nobotondocumentacionazure() {
    // Test name: no-boton-documentacion-azure
    // Step # | name | target | value
    // 1 | open | https://hmis2023-sesion04-freeweb.azurewebsites.net/index.html | 
    driver.get("https://hmis2023-sesion04-freeweb.azurewebsites.net/index.html");
    // 2 | setWindowSize | 1021x727 | 
    driver.manage().window().setSize(new Dimension(1021, 727));
    // 3 | click | css=li:nth-child(6) > .icon | 
    driver.findElement(By.cssSelector("li:nth-child(6) > .icon")).click();
    // 4 | assertNotText | id=hero-title | Documentación de Azure
    assertThat(driver.findElement(By.id("hero-title")).getText(), is(not("Documentación de Azure")));
  }
  @Test
  public void nobotonhtml5() {
    // Test name: no-boton-html5
    // Step # | name | target | value
    // 1 | open | https://hmis2023-sesion04-freeweb.azurewebsites.net/index.html | 
    driver.get("https://hmis2023-sesion04-freeweb.azurewebsites.net/index.html");
    // 2 | setWindowSize | 1021x727 | 
    driver.manage().window().setSize(new Dimension(1021, 727));
    // 3 | click | linkText=HTML5 UP | 
    driver.findElement(By.linkText("HTML5 UP")).click();
    // 4 | assertNotText | css=.about > strong | spiffy HTML5\nsite templates
    assertThat(driver.findElement(By.cssSelector(".about > strong")).getText(), is(not("spiffy HTML5\\\\nsite templates")));
  }
  @Test
  public void nobotongit() {
    // Test name: no-boton-git
    // Step # | name | target | value
    // 1 | open | https://hmis2023-sesion04-freeweb.azurewebsites.net/index.html | 
    driver.get("https://hmis2023-sesion04-freeweb.azurewebsites.net/index.html");
    // 2 | setWindowSize | 1021x727 | 
    driver.manage().window().setSize(new Dimension(1021, 727));
    // 3 | click | css=.fa-git-alt | 
    driver.findElement(By.cssSelector(".fa-git-alt")).click();
    // 4 | assertNotText | css=h1 | Book
    assertThat(driver.findElement(By.cssSelector("h1")).getText(), is(not("Book")));
  }
  @Test
  public void nobotonrepohmis() {
    // Test name: no-boton-repo-hmis
    // Step # | name | target | value
    // 1 | open | https://hmis2023-sesion04-freeweb.azurewebsites.net/index.html | 
    driver.get("https://hmis2023-sesion04-freeweb.azurewebsites.net/index.html");
    // 2 | setWindowSize | 1021x727 | 
    driver.manage().window().setSize(new Dimension(1021, 727));
    // 3 | click | css=li:nth-child(3) > .icon | 
    driver.findElement(By.cssSelector("li:nth-child(3) > .icon")).click();
    // 4 | assertNotText | css=.flex-1 > .color-fg-muted > div | Grado en Ingeniería Informática -Universidad de Almería
    assertThat(driver.findElement(By.cssSelector(".flex-1 > .color-fg-muted > div")).getText(), is(not("Grado en Ingeniería Informática -Universidad de Almería")));
  }
}
